CREATE USER IF NOT EXISTS 'timeclock_app'@'%' IDENTIFIED BY '?1r8G7|bBV+T!L9y';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES
    ON timeclock.* TO 'timeclock_app'@'%';
FLUSH PRIVILEGES;
